name: computer-vision
channels:
  - conda-forge
dependencies:
  - python=3.12
  - opencv
  - qt-main
  - pillow
  - transformers
  - torchvision
  - onnx
  - onnxruntime
  - onnxscript
  - fontconfig
  - freetype
  - libpng
  - numpy
  - pip:
      - distinctipy
