name: computer-vision
channels:
  - conda-forge
dependencies:
  - python=3.12
  - opencv
  - qt-main
  - pillow
  - transformers
  - pytorch
  - pytorch-cuda
  - torchvision
  - fontconfig
  - freetype
  - libpng
  - numpy
